set(LIBCPPLOG_INCLUDE_DIRS ${LIBCPPLOG_DIR}/include)
set(LIBCPPLOG_LIBRARY_DIR ${LIBCPPLOG_DIR}/lib)
set(LIBCPPLOG_LIB_NAME libcpplog)

if (WIN32)
    string(TOUPPER "${CMAKE_BUILD_TYPE}" CMAKE_BUILD_TYPE_TO_UPPER)
    if (${CMAKE_BUILD_TYPE_TO_UPPER} STREQUAL "DEBUG")
        set(LIBCPPLOG_LIB_NAME libcpplogd)
    endif()  
endif()

set(LIBCPPLOG ${LIBCPPLOG_DIR}/lib/${LIBCPPLOG_LIB_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX})