@startuml class-diagram

title libcpplog public API class diagram

package cpplog::logger {

    enum LogLevel {
        Error
        Info
        Result
        Warning
    }
    hide LogLevel methods

    enum LogComponent {
        LogLevel
        Context
        ContextLong
        TimeStamp
    }
    hide LogComponent methods

    class LogRequest {
        + LogRequest()
        + LogRequest(LogLevel)
        ..
        + {static} logLevel() : LogLevel
        + {static} logLevel(LogLevel) : LogLevel
        + {static} context() : LogRequest::Context
        + {static} timeStamp() : LogRequest::TimeStamp
        + {static} functionName() : LogRequest::FunctionName
    }

    class LogFormat << (D,#0077AA) >> {
        LogComponent[ ]
    }
    hide LogFormat methods

    class Logger {
        + Logger(ostream&, LogFormat)
        ..
        + setOutput(ostream&) : void
        + setFormat(LogFormat) : void
        ..
        + log(string) : void
        + log(LogLevel, string) : void
        + logOnce(string) : void
        + logOnce(LogLevel, string) : void
        + log(string, LogRequest::FunctionName) : void
        + log(LogLevel, string, LogRequest::FunctionName) : void
        + log(exception&) : void
        + log(LogLevel, exception&) : void
        ..
        + operator<<(string) : Logger&
        + operator<<(float) : Logger&
        + operator<<(LogRequest) : Logger&
        + operator<<(enum LogLevel) : Logger&
        + operator<<(LogRequest::Context) : Logger&
        + operator<<(LogRequest::TimeStamp) : Logger&
        + operator<<(LogRequest::FunctionName) : Logger&
    }

    class "<<globals>>" as globals << (G,#FF77FF) >> {
        logger : Logger
        ..
        setOutput(ostream&) : void
        setFormat(LogFormat) : void
        ..
        log(string) : void
        log(LogLevel, string) : void
        logOnce(string) : void
        logOnce(LogLevel, string) : void
        log(string, LogRequest::FunctionName) : void
        log(LogLevel, string, LogRequest::FunctionName) : void
        log(exception&) : void
        log(LogLevel, exception&) : void
    }
}

@enduml