@startuml class-diagram

title libcpplog public class diagram

package cpplog::logger {

    enum LogLevel {
        Error
        Info
        Result
        Warning
    }
    hide LogLevel methods

    enum LogComponent {
        LogLevel
        Context
        ContextLong
        TimeStamp
    }
    hide LogComponent methods

    class LogStream {
        + LogStream()
        + LogStream(LogLevel)
        ..
        + {static} logLevel() : LogLevel
        + {static} logLevel() : LogLevel
        + {static} context() : source_location
        + {static} timeStamp() : LogStream::TimeStamp
    }

    class LogFormat << (D,#0077AA) >> {
        LogComponent[ ]
    }
    hide LogFormat methods

    class Logger {
        + Logger(ostream&, LogFormat)
        ..
        + setOutput(ostream&) : void
        + setFormat(LogFormat) : void
        ..
        + log(string) : void
        + log(LogLevel, string) : void
        + logOnce(string) : void
        + logOnce(LogLevel, string) : void
        ..
        + operator<<(string) : Logger&
        + operator<<(float) : Logger&
        + operator<<(LogStream) : Logger&
        + operator<<(enum LogLevel) : Logger&
        + operator<<(LogStream::TimeStamp) : Logger&
        + operator<<(source_location) : Logger&
    }

    class "<<globals>>" as globals << (G,#FF77FF) >> {
        logger : Logger
        ..
        setOutput(ostream&) : void
        setFormat(LogFormat) : void
        ..
        log(string) : void
        log(LogLevel, string) : void
        logOnce(string) : void
        logOnce(LogLevel, string) : void
    }
}

@enduml