@startuml package-diagram

title libcpplog package diagram

package "Public Interface" as API

package logger {
    [Logger]
    [Log]
    [LogLevel]
    [LogFormat]
    [LogComponent]
    [LogStream]

    package decorator {
        [Decorator]
        [Message]
        [LogLevel]
        [TimeStamp]

        package context {
            [Context]
            [Long]
            [Short]
        }
    }
}

package debug {
    [Debug]
}

logger ..> debug : <<access>>

[Logger] ..> decorator : <<access>>

API ..> Logger : <<import>>
API ..> Log : <<import>>
API ..> LogLevel : <<import>>
API ..> LogFormat : <<import>>
API ..> LogComponent : <<import>>
API ..> LogStream : <<import>>
API ..> Debug : <<import>>

@enduml