include(GNUInstallDirs)

if(NOT DEFINED libcpplog_INSTALL_INCLUDEDIR)
  set(libcpplog_INSTALL_INCLUDEDIR "${CMAKE_INSTALL_INCLUDEDIR}")
endif()

if(NOT DEFINED libcpplog_INSTALL_BINDIR)
  set(libcpplog_INSTALL_BINDIR "${CMAKE_INSTALL_BINDIR}")
endif()

if(NOT DEFINED libcpplog_INSTALL_LIBDIR)
  set(libcpplog_INSTALL_LIBDIR "${CMAKE_INSTALL_LIBDIR}")
endif()

if(NOT DEFINED libcpplog_INSTALL_DATADIR)
  set(libcpplog_INSTALL_DATADIR "${CMAKE_INSTALL_DATADIR}")
endif()

if(NOT DEFINED libcpplog_INSTALL_CMAKECONFIGDIR)
  set(libcpplog_INSTALL_CMAKECONFIGDIR "${libcpplog_INSTALL_DATADIR}/${CMAKE_PROJECT_NAME}/cmake")
endif()