@startuml utils-tree-class-diagram

title utils tree class diagram

class Node<TId> {
    == public ==
    + Node(TId)
    ..
    + getId() : TId
    + add(Node<TId>) : void
    + getChildNodes() : Node<TId>[]&
    ..
    + begin() : iterator
    + end() : iterator
    + cbegin() : const_iterator
    + cend() : const_iterator
    == private ==
    - id : TId

}

Node "*" *-- Node

@enduml